apiVersion: v1
kind: Secret
metadata:
  name: {{ include "snmp-olt-zte.fullname" . }}
  labels:
    {{- include "snmp-olt-zte.labels" . | nindent 4 }}
type: Opaque
data:
  SNMP_COMMUNITY: {{ .Values.snmp.community | b64enc | quote }}
  REDIS_PASSWORD: {{ include "snmp-olt-zte.redisPassword" . | b64enc | quote }}
  API_KEY: {{ .Values.auth.apiKey | b64enc | quote }}
  API_USERS: {{ .Values.auth.apiUsers | b64enc | quote }}
  {{- if and .Values.trap.enabled (not .Values.trap.existingSecret) }}
  TRAP_WEBHOOK_URL: {{ .Values.trap.webhookURL | b64enc | quote }}
  {{- end }}
  {{- if and (not .Values.olt.olts) .Values.olt.oltsFile }}
  olts.json: {{ .Values.olt.oltsFile | b64enc | quote }}
  {{- end }}
