apiVersion: v2
name: snmp-olt-zte-c320
description: Monitoring OLT ZTE C320 via SNMP - REST API with Redis caching
type: application
version: 2.1.1
appVersion: "2.1.1"

dependencies:
  - name: redis
    version: "~18.x"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
