apiVersion: v2
name: snmp-olt-zte
description: Monitoring ZTE C320 & C300 OLTs via SNMP — multi-OLT REST API with Redis caching
type: application
version: 3.2.1
appVersion: "3.2.0"

dependencies:
  - name: redis
    version: "~18.x"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
