apiVersion: v1
kind: Secret
metadata:
  name: {{ include "snmp-olt-zte-c320.fullname" . }}
  labels:
    {{- include "snmp-olt-zte-c320.labels" . | nindent 4 }}
type: Opaque
data:
  SNMP_COMMUNITY: {{ .Values.snmp.community | b64enc | quote }}
  REDIS_PASSWORD: {{ include "snmp-olt-zte-c320.redisPassword" . | b64enc | quote }}
  API_KEY: {{ .Values.auth.apiKey | b64enc | quote }}
