apiVersion: v1
kind: Service
metadata:
  name: snmp-olt-zte-c320
  namespace: olt-monitoring
  labels:
    app.kubernetes.io/name: snmp-olt-zte-c320
    app.kubernetes.io/component: api-server
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: snmp-olt-zte-c320
  ports:
    - name: http
      port: 8081
      targetPort: http
      protocol: TCP
    - name: trap-udp
      port: 1620
      targetPort: trap-udp
      protocol: UDP
