apiVersion: apps/v1
kind: Deployment
metadata:
  name: snmp-olt-zte-c320
  namespace: olt-monitoring
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: snmp-olt-zte-c320
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "2000m"
